import os

AUTHOR = 'Zaur Nasibov'
SITENAME = "Zaur's Thoughts"
SITETITLE = "Zaur's Thoughts"
SITESUBTITLE = "Zaurun Fikirləri"
SITELOGO = '/static/images/logo.png'
FAVICON = '/static/images/favicon.png'
COPYRIGHT_YEAR = 2024

PATH = 'content'

TIMEZONE = 'Europe/Helsinki'

DEFAULT_LANG = 'en'

DATE_FORMATS = {
    'en': '%d %B %Y'
}

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Social widget
SOCIAL = (
    ('linkedin', 'https://www.linkedin.com/in/zaur-nasibov-44610853/'),
    ('github', 'https://github.com/basicwolf'),
    ('rss', '/feeds/atom.xml'),
)


MAIN_MENU = True
DISQUS_SITENAME = None
DISPLAY_PAGES_ON_MENU = True
DISPLAY_CATEGORIES_ON_MENU = True

MENUITEMS = (
    ('Archives', '/archives.html'),
    ('Tags', '/tags.html'),
)

LINKS = (
    ('<strong>Articles</strong>', '/posts.html'),
    ('Books', '/category/books.html'),
)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

##### END OF GENERATED BY pelican-quickstart #####

MYDIR = os.path.dirname(__file__)

ARTICLES_PATH = ['articles']

PLUGINS_PATH = os.path.abspath(os.path.join(MYDIR, '../pelican-plugins'))
PLUGIN_PATHS = [PLUGINS_PATH]
PLUGINS = [
    'plantuml',
    'post_stats',
    'pelican_redirect',
    'neighbors',
]

ARTICLE_URL = 'posts/{date:%Y}/{date:%m}/{date:%d}/{slug}.html'
ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%m}/{date:%d}/{slug}.html'
PAGE_URL = 'pages/{slug}.html'
PAGE_SAVE_AS = 'pages/{slug}.html'

INDEX_SAVE_AS = 'posts.html'

PYGMENTS_RST_OPTIONS = {'linenos': 'table'}

STATIC_PATHS = [
    'articles',
    'pages',
    'images',
    'static',
    'extra/CNAME'
]

EXTRA_PATH_METADATA = {
    'extra/CNAME': {'path': 'CNAME'},
}

CUSTOM_CSS = '/static/css/extra.css'

THEME = '../Flex'

CACHE_CONTENT = True
LOAD_CONTENT_CACHE = True
