name: Build and Publish the blog

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        description: 'Should the blog be published?'
        required: false
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

env:
  LC_ALL: en_US.UTF8
  DEBUG: 1
  ACCESS_TOKEN_BASICWOLF_GITHUB_IO: ${{ secrets.ACCESS_TOKEN_BASICWOLF_GITHUB_IO }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.ACCESS_TOKEN_BASICWOLF_GITHUB_IO}}
          submodules: 'true'

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml
          make install

      - name: "Build the blog"
        run: make build

      - name: "Publish the blog"
        if: |
          inputs.publish == 'yes' ||
          !contains(github.event.head_commit.message, 'ci:skip')
        run: make publish-from-ci
